Payroll_Mvc/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Threading.Tasks;

using NHibernate;
using Domain.Model;
using Payroll_Mvc.Helpers;

namespace Payroll_Mvc.Controllers
{
    public class ApplicationController : AsyncController
    {
        //
        // GET: /Application/

        public ActionResult Login()
        {
            if (Request.IsAuthenticated)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
            }

            return View();
        }

        [HttpPost]
        public ActionResult Login(FormCollection fc)
        {
            string username = fc.Get("username");
            string password = fc.Get("password");

            ISession se = NHibernateHelper.CurrentSession;
            User user = Domain.Model.User.Authenticate(se, username, password);

            if (user != null)
            {
                Session["user_id"] = user.Id;
                if (user.Role == Domain.Model.User.ADMIN)
                {
                    Session["admin_id"] = user.Id;
                    FormsAuthentication.SetAuthCookie(username, true);
                    return RedirectToRoute("Admin_index");
                }

                else
                {
                    Employee employee = user.Employee;
                    if (employee != null)
                    {
                        Session["employee_id"] = employee.Id;
                        Session["staff_id"] = employee.Staffid;
                        FormsAuthentication.SetAuthCookie(username, true);
                        return RedirectToRoute("User_index");
                    }

                    else
                        ViewBag.alert = @"No employee record found. Please contact the administrator 
                                          to create your employee record.";
                }
            }

            else
                ViewBag.alert = "Incorrect username or password";

            return View("Login");
        }

        public ActionResult Logout()
        {
            Session.Clear();
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

Payroll_Mvc/Views/Application/Login.cshtml
@{
    ViewBag.title = "Payroll System: Log In";
    Layout = "~/Views/Layouts/_Application.cshtml";
}

<div class="login_box ui-corner-all ui-state-hover">
    <div class="msg ui-state-highlight ui-corner-all">Please log in to access the application:</div>

    @if (ViewBag.notice != null)
    {
        <div class="notice ui-state-hover ui-corner-all">@ViewBag.notice</div>
    }
    @if (ViewBag.alert != null)
    {
        <div class="errorblock ui-state-error ui-corner-all">@ViewBag.alert</div>
    }
    @using (Html.BeginForm("Login", "Application", FormMethod.Post))
    {
        <div class="row">
            <label for="username" class="editor-label">Username</label>
            <input name="username" type="text" class="text-box" x-webkit-speech="x-webkit-speech" value="admin" />
        </div>
        <div class="row">
            <label for="password" class="editor-label">Password</label>
            <input name="password" type="password" class="text-box" x-webkit-speech="x-webkit-speech" value="admin123" />
        </div>
        
        <div class="msg ui-corner-all">
            <input type="submit" class="hover msg login_btn ui-state-hover ui-corner-all" value="Log In" />
        </div>
    }
</div>